name: garf
favicon: null
layout_spectrum: 1
typography_spectrum: 0.70462
title: Garf OÃœ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d1611'
    - '#7ca3da'
    - '#4767a2'
    - '#fdfef6'
    - '#233a6c'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 1
purpose: []
